[[customizations.user]]
name = "guest"
description = "Guest account in group wheel"
password = "password2020" 
home = "/home/guest"
shell = "/usr/bin/bash"
groups = ["users", "wheel"]
uid = 2020
gid = 2020

_________________________________________________________________
Note that the password can be an encrypted string.
Generate one like this:
python3 -c "import crypt, getpass; print(crypt.crypt(getpass.getpass(), crypt.METHOD_SHA512))"

Enter a password when prompted, and the encrypted version will be displayed.



